-- 1. DISPLAY DEPARTMENT NAME USING DEPTNO
SELECT EMPNO, ENAME,
CASE DEPTNO
WHEN 10 THEN 'ACCOUNTING'
WHEN 20 THEN 'RESEARCH'
WHEN 30 THEN 'SALES'
WHEN 40 THEN 'OPERATIONS'
END AS DEPARTMENT_NAME
FROM EMPLOYEE;


-- 2. DISPLAY YOUR AGE IN DAYS
SELECT DATEDIFF(CURDATE(), '2002-08-15') AS AGE_IN_DAYS;


-- 3. DISPLAY YOUR AGE IN MONTHS
SELECT TIMESTAMPDIFF(MONTH, '2002-08-15', CURDATE()) AS AGE_IN_MONTHS;


-- 4. DISPLAY CURRENT DATE IN FORMATE
SELECT DATE_FORMAT(NOW(), '%D %M %W %Y');


-- 5. DISPLAY EMPLOYEE JOINING MESSAGE
SELECT CONCAT(ENAME, ' HAS JOINED ON ',
DATE_FORMAT(HIREDATE, '%W %D %M %Y'))
FROM EMPLOYEE;


-- 6. DISPLAY THE JOINING DATE OF SCOTT
SELECT CONCAT('SCOTT HAS JOINED THE COMPANY ON ',
DATE_FORMAT(HIREDATE, '%W %D %M %Y'))
FROM EMPLOYEE
WHERE ENAME = 'SCOTT';


-- 7. DISPLAY NEXT SATURDAY
SELECT DATE_ADD(CURDATE(), INTERVAL (7 - DAYOFWEEK(CURDATE())) DAY);


-- 8. DISPLAY CURRENT TIME
SELECT DATE_FORMAT(NOW(), '%h:%i:%s %p');


-- 9 DISPLAY DATE BEFORE 3 MONTHS
SELECT DATE_SUB(CURDATE(), INTERVAL 3 MONTH);


-- 10. EMPLOYEES JOINED IN DECEMBER
SELECT *
FROM EMPLOYEE
WHERE MONTH(HIREDATE) = 12;


-- 11. MATCH DAY OF HIREDATE WITH LAST 2 DIGIT OF SAL
SELECT *
FROM EMPLOYEE
WHERE DAY(HIREDATE) = RIGHT(SAL, 2);


-- 12. SALARY CONDITION WITH YEAR
SELECT *
FROM EMPLOYEE
WHERE SAL * 0.10 = YEAR(HIREDATE);


-- 13. EMPLOYEES JOINED BEFORE 15 MONTHS AGO
SELECT *
FROM EMPLOYEE
WHERE HIREDATE < DATE_SUB(CURDATE(), INTERVAL 15 MONTH);


-- 14. EMPLOYEES JOINED BEFORE 15TH DAY OF MONTH
SELECT *
FROM EMPLOYEE
WHERE DAY(HIREDATE) < 15;


-- 15. EMPLOYEES WITH NOT NULL VALUES
SELECT *
FROM EMPLOYEE
WHERE HIREDATE IS NOT NULL
AND DEPTNO IS NOT NULL; 

