-- Q1
SELECT * FROM EMPLOYEE
WHERE HIREDATE < '1980-06-30'
OR HIREDATE > '1981-12-31';

-- Q2
SELECT ENAME FROM EMPLOYEE
WHERE ENAME LIKE '_A%';

-- Q3
SELECT ENAME FROM EMPLOYEE
WHERE ENAME LIKE '_____';

-- Q4 SAME AS 2

-- Q5
SELECT ENAME FROM EMPLOYEE
WHERE JOB NOT IN ('SALESMAN', 'CLERK', 'ANALYST');

-- Q6
SELECT ENAME, SAL*12 AS ANNUAL_SALARY
FROM EMPLOYEE
ORDER BY ANNUAL_SALARY DESC;

-- Q7
SELECT ENAME, SAL,
SAL*0.15 AS HRA,
SAL*0.10 AS DA,
SAL*0.05 AS PF,
(SAL + (SAL*0.15) + (SAL*0.10) - (SAL*0.05)) AS TOTALSAL
FROM EMPLOYEE
ORDER BY TOTALSAL;

-- Q8
UPDATE EMPLOYEE
SET SAL = SAL*1.10
WHERE COMM IS NULL;

-- Q9
SELECT ENAME, SAL
FROM EMPLOYEE
WHERE SAL*1.20 > 3000;

-- Q10
SELECT * FROM EMPLOYEE
WHERE LENGTH(SAL) >= 3;

