-- 1.TOTAL NUMBER OF EMPLOYEES
SELECT COUNT(*) FROM EMPLOYEE;

-- 2.TOTAL SALARY PAID TO ALL EMPLOYEES
SELECT SUM(SAL) FROM EMPLOYEE;

-- 3.MAXIMUM SALARY
SELECT MAX(SAL) FROM EMPLOYEE;

-- 4.MINIMUM SALARY
SELECT MIN(SAL) FROM EMPLOYEE;

-- 5.AVERAGE SALARY
SELECT AVG(SAL) FROM EMPLOYEE;

-- 6.MAXIMUM SALARY PAID TO CLERK
SELECT MAX(SAL) FROM EMPLOYEE WHERE JOB = 'CLERK';

-- 7.MAXIMUM SALARY IN DEPT NO 20
SELECT MAX(SAL) FROM EMPLOYEE WHERE DEPTNO = 20;

-- 8.MINIMUM SALARY PAID TO SALESMAN
SELECT MIN(SAL) FROM EMPLOYEE WHERE JOB = 'SALESMAN';

-- 9.AVERAGE SALARY DRAWN BY MANAGERS
SELECT AVG(SAL) FROM EMPLOYEE WHERE JOB = 'MANAGER';

-- 10.TOTAL SALARY DRAWN BY ANALYST IN DEPT NO 40
SELECT SUM(SAL) FROM EMPLOYEE WHERE JOB = 'ANALYST' AND DEPTNO = 40;

-- 11.EMPLOYEE NAMES IN UPPERCASE
SELECT UPPER(ENAME) FROM EMPLOYEE;

-- 12.EMPLOYEE NAMES IN LOWERCASE
SELECT LOWER(ENAME) FROM EMPLOYEE;

-- 13.EMPLOYEE NAMES IN PROPER CASE
SELECT CONCAT(UPPER(SUBSTRING(ENAME,1,1)), LOWER(SUBSTRING(ENAME,2))) FROM EMPLOYEE;

-- 14.LENGTH OF YOUR NAME
SELECT LENGTH('TAUFIQUE');

-- 15.LENGTH OF ALL EMPLOYEE NAMES
SELECT ENAME, LENGTH(ENAME) FROM EMPLOYEE;