-- List all employees and jobs in department 30 in descending order by salary
SELECT ENAME, JOB, SAL
FROM EMPLOYEE
WHERE DEPTNO = 30
ORDER BY SAL DESC;

-- LIST JOB AND DEPARTMENT NUMBER OF EMPLOYEES WHOSE NAME IS 5 LETTERS LONG, BEGINS WITH ‘A’ AND ENDS WITH ‘N’
SELECT JOB, DEPTNO
FROM EMPLOYEE
WHERE ENAME LIKE 'A___N';

-- DISPLAY THE NAME OF EMPLOYEES WHOSE NAME STARTS WITH ALPHABET S
SELECT ENAME
FROM EMPLOYEE
WHERE ENAME LIKE 'S%';

-- DISPLAY THE NAMES OF EMPLOYEES WHOSE NAME ENDS WITH ALPHABET SSELECT ENAME
FROM EMPLOYEE
WHERE ENAME LIKE '%S';

-- DISPLAY THE NAMES OF EMPLOYEES WORKING IN DEPT 10 OR 20 OR 40 OR WORKING AS CLERK, SALESMAN OR ANALYST
SELECT ENAME
FROM EMPLOYEE
WHERE DEPTNO IN (10, 20, 40)
OR JOB IN ('CLERK', 'SALESMAN', 'ANALYST');

-- DISPLAY EMPLOYEE NUMBER AND NAME OF EMPLOYEES WHO EARN COMMISSION
SELECT EMPNO, ENAME
FROM EMPLOYEE
WHERE COMM IS NOT NULL;

-- DISPLAY EMPLOYEE NUMBER AND TOTAL SALARY FOR EACH EMPLOYEE
SELECT EMPNO, SAL + IFNULL(COMM, 0) AS TOTALSALARY
FROM EMPLOYEE;

-- DISPLAY EMPLOYEE NUMBER AND ANNUAL SALARY FOR EACH EMPLOYEE
SELECT EMPNO, SAL * 12 AS ANNUAL_SALARY
FROM EMPLOYEE;

-- DISPLAY NAMES OF ALL EMPLOYEES WORKING AS CLERKS AND DRAWING SALARY MORE THAN 3000
SELECT ENAME
FROM EMPLOYEE
WHERE JOB = 'CLERK'
AND SAL > 3000;

-- DISPLAY NAMES OF EMPLOYEES WORKING AS CLERK, SALESMAN OR ANALYST AND DRAWING SALARY MORE THAN 3000
SELECT ENAME
FROM EMPLOYEE
WHERE JOB IN ('CLERK', 'SALESMAN', 'ANALYST')
AND SAL > 3000;